
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://fonts.googleapis.com/css?family=Ubuntu&display=swap" rel="stylesheet">
<link href="styling.css" rel="stylesheet" type="text/css">
</head>
<body>
<h1 class="borderDesign gradient" style = "text-align: center; font-family: 'Ubuntu',serif;font-size:30px;">Welcome To Appa Pizza (Made with pure devotion)</h1>
<img class="responsive" src="1.png" alt="Cheese Brust" align="left">
<img class="responsive" src="2.png" alt="Pan Pizza" align="right">
<div style="padding:10%;">
<center>
<form  method="POST" action="" name="form"  >
<input class="btn btn1" type="button" name="cbp" value="Cheese Burst Pizza" onClick="window.location='cbp.php';" /><br>
<input class="btn btn1" type="button" name="pp" value="Pan Pizza" onClick="window.location='pan.php';" /><br>
<input class="btn btn1" type="button" name="logout" value="Logout" onClick="window.location='index.php';" />
</form>
</center>
</div>
</body>
</html>
